require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - 'vendor/**/*'
    - 'script/**/*'

Gemspec/RequiredRubyVersion:
  Enabled: true

Style/Documentation:
  Enabled: false  # We have README

Style/StringLiterals:
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'

RSpec/MultipleExpectations:
  Max: 5

RSpec/ExampleLength:
  Max: 15
